# Generated by Django 4.2.7 on 2023-11-06 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moneyflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "tili", "verbose_name_plural": "tilit"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "kategoria", "verbose_name_plural": "kategoriat"},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "dokumentti", "verbose_name_plural": "dokumentit"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "tapahtuma", "verbose_name_plural": "tapahtumat"},
        ),
        migrations.AddField(
            model_name="transaction",
            name="name",
            field=models.CharField(max_length=100, null=True, verbose_name="nimi"),
        ),
        migrations.AlterField(
            model_name="account",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="pankitili"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="luotu"),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nimi"),
        ),
        migrations.AlterField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="omistaja",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="luotu"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nimi"),
        ),
        migrations.AlterField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="omistaja",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="moneyflow.category",
                verbose_name="yläkategoria",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="luotu"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="docs/%Y-%m-%d/", verbose_name="tiedosto"),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="nimi"),
        ),
        migrations.AlterField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="omistaja",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("BILL", "Lasku"),
                    ("RECEIPT", "Kuitti"),
                    ("ESTIMATION", "Laskelma"),
                    ("OTHER", "Muu"),
                ],
                max_length=20,
                verbose_name="tyyppi",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="moneyflow.account",
                verbose_name="tili",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="summa"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="moneyflow.category",
                verbose_name="kategoria",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="luotu"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(verbose_name="päivämäärä"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="transactions",
                to="moneyflow.document",
                verbose_name="dokumentit",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="state",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "Tuleva"),
                    ("DONE", "Tapahtunut"),
                    ("CANCELED", "Peruttu"),
                    ("MISSED", "Mennyt"),
                ],
                max_length=20,
                verbose_name="tila",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("INCOME", "Tulo"), ("EXPENSE", "Meno")],
                max_length=20,
                verbose_name="tyyppi",
            ),
        ),
    ]
