# Generated by Django 4.2.7 on 2023-11-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneyflow", "0002_alter_account_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="kuvaus"
            ),
        ),
    ]
