# Generated by Django 4.2.7 on 2023-11-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneyflow", "0004_category_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category",
        ),
        migrations.AddField(
            model_name="transaction",
            name="category2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Car", "Auto"),
                    ("Food", "Ruoka"),
                    ("Home", "Koti"),
                    ("Salary", "Palkka"),
                    ("Savings", "Säästöt"),
                    ("Shopping", "Shoppailu"),
                    ("Transport", "Liikenne"),
                    ("Travel", "Matkustus"),
                    ("Utilities", "Laskut"),
                    ("Other", "Muu"),
                ],
                max_length=20,
                null=True,
                verbose_name="kategoria",
            ),
        ),
    ]
