# Generated by Django 4.2.7 on 2023-11-06 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moneyflow", "0005_remove_category_category_transaction_category2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="category2",
        ),
    ]
